### ISSUE TITLE
Erro (Access violation) em Windows 64 bits

### ISSUE THREAD

**Issue by uelitonmelo** [HashLoad/handle-exception#20]
Quando o projeto é compilado em 32 bits funciona.
Quando compilo para 64 bits apresenta esse erro
"Access violation at address 000000000035EF25 in module 'ServerEcommerce.exe'. Read of address 00000000FFFFFFDF"

exemplo do código:
  raise EHorseException.New.Error('Usuário/Senha inválido!').Status(THTTPStatus.Unauthorized);

**Comment by viniciussanchez** [comment]
Bom dia.. consegue nos enviar um projeto de exemplo com o problema em questão? Aqui utilizo em 64 bits e funciona perfeitamente... deve ser algum outro detalhe
